name: ci-windows

env:
  CI: GITHUB

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on: [push]

jobs:
  ci-job:
    strategy:
      fail-fast: false
      matrix:
        toolset: [v141, v142, v143]
        target: [x64, Win32, ARM, ARM64]
        build-type: [Debug, Release]
        os: [windows-latest, windows-2019]
        exclude:
          - os: windows-latest
            toolset: v141
          - os: windows-2019
            toolset: v143
          - os: windows-latest
            target: ARM
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: ci-step
      shell: bash
      run: |
        . ci.sh "-A|${{ matrix.target }}|-T|${{ matrix.toolset }}|-DCMAKE_BUILD_TYPE=${{ matrix.build-type }}" \
           "--config|${{ matrix.build-type }}" "--build-config|${{ matrix.build-type }}"
