name: ci-wincxx

env:
  CI: GITHUB

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on: [push]

jobs:
  ci-job:
    strategy:
      fail-fast: false
      matrix:
        toolset: [v141, v142, v143]
        cxx: [11, 14, 17, 20]
        os: [windows-latest, windows-2019]
        build-type: [Debug, Release]
        target: [x64, ARM]
        exclude:
          - os: windows-latest
            toolset: v141
          - os: windows-2019
            toolset: v143
          - target: x64
            build-type: Debug
          - target: ARM
            build-type: Release
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: ci-step
      shell: bash
      run: |
        . ci.sh "-A|${{ matrix.target }}|-T|${{ matrix.toolset }}|-DCMAKE_BUILD_TYPE=${{ matrix.build-type }}|-DCMAKE_CXX_STANDARD=${{ matrix.cxx }}" \
          "--config|${{ matrix.build-type }}" "--build-config|${{ matrix.build-type }}"
